const defaultResources = [
  // CS-50 Resources
  {
    id: 1,
    title: "CS50 Introduction to Computer Science - Harvard",
    description: "الدورة الرسمية من جامعة هارفارد لتعلم أساسيات علوم الحاسوب",
    url: "https://cs50.harvard.edu/x/",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 2,
    title: "CS50 Arabic - ترجمة عربية",
    description: "ترجمة عربية لدورة CS50 من جامعة هارفارد",
    url: "https://www.youtube.com/playlist?list=PLdFfKsmEokGSVnVS4LqA9qCJqA4r6rD8S",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 3,
    title: "CS50 Lecture 0 - Scratch",
    description: "محاضرة introducing to computational thinking with Scratch",
    url: "https://cs50.harvard.edu/x/2024/weeks/0/",
    type: "video",
    category: "cs50",
    subcategory: "scratch",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 4,
    title: "CS50 Lecture 1 - C",
    description: "مقدمة في لغة C وبرمجة الحاسوب",
    url: "https://cs50.harvard.edu/x/2024/weeks/1/",
    type: "video",
    category: "cs50",
    subcategory: "c-language",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 5,
    title: "CS50 Lecture 2 - Arrays",
    description: "تعلم المصفوفات والبيانات في لغة C",
    url: "https://cs50.harvard.edu/x/2024/weeks/2/",
    type: "video",
    category: "cs50",
    subcategory: "arrays",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 6,
    title: "CS50 Lecture 3 - Algorithms",
    description: "خوارزميات البحث والترتيب",
    url: "https://cs50.harvard.edu/x/2024/weeks/3/",
    type: "video",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 7,
    title: "CS50 Lecture 4 - Memory",
    description: "إدارة الذاكرة في البرمجة",
    url: "https://cs50.harvard.edu/x/2024/weeks/4/",
    type: "video",
    category: "cs50",
    subcategory: "memory",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 8,
    title: "CS50 Lecture 5 - Data Structures",
    description: "هياكل البيانات المتقدمة",
    url: "https://cs50.harvard.edu/x/2024/weeks/5/",
    type: "video",
    category: "cs50",
    subcategory: "data-structures",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 9,
    title: "CS50 Lecture 6 - Python",
    description: "مقدمة في لغة بايثون",
    url: "https://cs50.harvard.edu/x/2024/weeks/6/",
    type: "video",
    category: "cs50",
    subcategory: "python",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 10,
    title: "CS50 Lecture 7 - SQL",
    description: "قواعد البيانات SQL",
    url: "https://cs50.harvard.edu/x/2024/weeks/7/",
    type: "video",
    category: "cs50",
    subcategory: "sql",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 11,
    title: "CS50 Lecture 8 - HTML, CSS, JavaScript",
    description: "تطوير الويب الأساسي",
    url: "https://cs50.harvard.edu/x/2024/weeks/8/",
    type: "video",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 12,
    title: "CS50 Lecture 9 - Flask",
    description: "تطوير تطبيقات الويب ببايثون",
    url: "https://cs50.harvard.edu/x/2024/weeks/9/",
    type: "video",
    category: "cs50",
    subcategory: "flask",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 13,
    title: "CS50 Final Project",
    description: "مشروع التخرج من CS50",
    url: "https://cs50.harvard.edu/x/2024/project/",
    type: "exercise",
    category: "cs50",
    subcategory: "project",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 14,
    title: "CS50 Study Notes - Arabic",
    description: "ملخصات دروس CS50 بالعربية",
    url: "https://cs50.harvard.edu/x/2024/notes/",
    type: "summary",
    category: "cs50",
    subcategory: "notes",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 15,
    title: "CS50 IDE - Online Compiler",
    description: "محرر الأكواد عبر الإنترنت من CS50",
    url: "https://ide.cs50.io/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Mathematics Resources
  {
    id: 100,
    title: "الرياضيات الأساسية للمبرمجين",
    description: "دورة شاملة في الأساسيات الرياضيات اللازمة للبرمجة",
    url: "https://www.khanacademy.org/math",
    type: "video",
    category: "math",
    subcategory: "algebra",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 101,
    title: "线性代数 - Linear Algebra",
    description: "جبر خطي لتعلم الذكاء الاصطناعي وتعلم الآلة",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    type: "video",
    category: "math",
    subcategory: "linear",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 102,
    title: "Calculus Made Easy",
    description: "كتاب مجاني لتعلم حساب التفاضل والتكامل",
    url: "https://www.gutenberg.org/files/33283/33283-pdf.pdf",
    type: "book",
    category: "math",
    subcategory: "calculus",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 103,
    title: "Discrete Mathematics - MIT OpenCourseWare",
    description: "رياضيات منفصلة من معهد ماساتشوستس للتقنية",
    url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/",
    type: "video",
    category: "math",
    subcategory: "discrete",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 104,
    title: "Probability and Statistics",
    description: "أساسيات الاحتمالات والإحصاء",
    url: "https://www.khanacademy.org/math/probability",
    type: "video",
    category: "math",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 105,
    title: "Mathematics for Computer Science",
    description: "كتاب الرياضيات لعلوم الحاسوب من MIT",
    url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/pages/readings/",
    type: "book",
    category: "math",
    subcategory: "discrete",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 106,
    title: "Algebra Fundamentals",
    description: "أساسيات الجبر للمبتدئين",
    url: "https://www.khanacademy.org/math/algebra",
    type: "video",
    category: "math",
    subcategory: "algebra",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 107,
    title: "Geometry Basics",
    description: "أساسيات الهندسة",
    url: "https://www.khanacademy.org/math/geometry",
    type: "video",
    category: "math",
    subcategory: "geometry",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 108,
    title: "Number Theory for Programming",
    description: "نظرية الأعداد للبرمجيات",
    url: "https://ocw.mit.edu/courses/18-781-theory-of-numbers-spring-2012/",
    type: "book",
    category: "math",
    subcategory: "number-theory",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Physics Resources
  {
    id: 200,
    title: "Physics for Scientists and Engineers",
    description: "فيزياء للمهندسين والعلماء",
    url: "https://www.khanacademy.org/science/physics",
    type: "video",
    category: "physics",
    subcategory: "mechanics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 201,
    title: "Classical Mechanics - MIT",
    description: "ميكانيكا كلاسيكية من MIT",
    url: "https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/",
    type: "video",
    category: "physics",
    subcategory: "mechanics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 202,
    title: "Electricity and Magnetism",
    description: "الكهرباء والمغناطيسية",
    url: "https://www.khanacademy.org/science/physics/electric-charge-field",
    type: "video",
    category: "physics",
    subcategory: "electricity",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 203,
    title: "Thermodynamics Basics",
    description: "أساسيات الديناميكا الحرارية",
    url: "https://www.khanacademy.org/science/physics/thermodynamics",
    type: "video",
    category: "physics",
    subcategory: "thermo",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 204,
    title: "Optics and Waves",
    description: "البصريات والموجات",
    url: "https://www.khanacademy.org/science/physics/waves-optics",
    type: "video",
    category: "physics",
    subcategory: "optics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 205,
    title: "Physics for Computer Science",
    description: "فيزياء م aplicada لعلوم الحاسوب",
    url: "https://www.edx.org/course/classical-mechanics",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Chemistry Resources
  {
    id: 300,
    title: "Chemistry - Khan Academy",
    description: "الكيمياء العامة من أكاديمية خان",
    url: "https://www.khanacademy.org/science/chemistry",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 301,
    title: "Organic Chemistry Basics",
    description: "أساسيات الكيمياء العضوية",
    url: "https://www.khanacademy.org/science/organic-chemistry",
    type: "video",
    category: "chemistry",
    subcategory: "organic",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 302,
    title: "General Chemistry - MIT",
    description: "كيمياء عامة من MIT",
    url: "https://ocw.mit.edu/courses/5-111-principles-of-chemical-science-fall-2014/",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 303,
    title: "Chemistry for Programming",
    description: "كيمياء مفيدة للمبرمجين - أساسياتatoms والجزيئات",
    url: "https://www.chemguide.co.uk/",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Statistics Resources
  {
    id: 400,
    title: "Statistics and Probability",
    description: "الإحصاء والاحتمالات من أكاديمية خان",
    url: "https://www.khanacademy.org/math/statistics-probability",
    type: "video",
    category: "statistics",
    subcategory: "descriptive",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 401,
    title: "Introduction to Statistical Learning",
    description: "مقدمة في التعلم الإحصائي",
    url: "https://www.statlearning.com/",
    type: "book",
    category: "statistics",
    subcategory: "inferential",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 402,
    title: "Probability for Computer Science",
    description: "الاحتمالات لعلوم الحاسوب",
    url: "https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/",
    type: "video",
    category: "statistics",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 403,
    title: "Think Stats - Free Book",
    description: "كتاب مجاني عن التفكير الإحصائي",
    url: "https://greenteapress.com/thinkstats2/html/index.html",
    type: "book",
    category: "statistics",
    subcategory: "descriptive",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Biology Resources
  {
    id: 500,
    title: "Biology - Khan Academy",
    description: "علم الأحياء من أكاديمية خان",
    url: "https://www.khanacademy.org/science/biology",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 501,
    title: "Introduction to Biology - MIT",
    description: "مقدمة في علم الأحياء من MIT",
    url: "https://ocw.mit.edu/courses/7-01-introductory-biology-fall-2011/",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 502,
    title: "Genetics and Genomics",
    description: "علم الوراثة والجينوم",
    url: "https://www.khanacademy.org/science/biology/classical-genetics",
    type: "video",
    category: "biology",
    subcategory: "genetics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 503,
    title: "Cell Biology",
    description: "علم الأحياء الخلوي",
    url: "https://www.khanacademy.org/science/biology/cells",
    type: "video",
    category: "biology",
    subcategory: "cell",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 504,
    title: "Bioinformatics for Programmers",
    description: "علم المعلومات الحيوية للمبرمجين",
    url: "https://www.coursera.org/learn/bioinformatics",
    type: "video",
    category: "biology",
    subcategory: "bioinformatics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // Additional CS Resources
  {
    id: 600,
    title: "Free Programming Books - GitHub",
    description: "مجموعة ضخمة من كتب البرمجة المجانية",
    url: "https://github.com/EbookFoundation/free-programming-books",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 601,
    title: "The Missing Semester of CS Education",
    description: "الفصل المفقود من تعليم علوم الحاسوب",
    url: "https://missing.csail.mit.edu/",
    type: "video",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 602,
    title: "How to Design Programs",
    description: "كيفية تصميم البرامج - كتاب مجاني",
    url: "https://htdp.org/",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 603,
    title: "Structure and Interpretation of Computer Programs",
    description: "هيكل وتفسير برامج الحاسوب - كتاب أيقوني",
    url: "https://mitpress-9780262512008.s3.amazonaws.com/684096ec47af4ad788596b546a8a3b59/SICPFullText.pdf",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 604,
    title: "Introduction to Algorithms (CLRS)",
    description: "مقدمة في الخوارزميات - الكتاب الشامل",
    url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/",
    type: "book",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 605,
    title: "CS50 Study Group - Facebook",
    description: "مجموعة دراسة CS50 على فيسبوك",
    url: "https://www.facebook.com/groups/cs50/",
    type: "link",
    category: "cs50",
    subcategory: "community",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 606,
    title: "W3Schools - Web Development",
    description: "تعلم تطوير الويب من W3Schools",
    url: "https://www.w3schools.com/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 607,
    title: "MDN Web Docs",
    description: "توثيق تطوير الويب من Mozilla",
    url: "https://developer.mozilla.org/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 608,
    title: "Python Official Documentation",
    description: "التوثيق الرسمي لغة بايثون",
    url: "https://docs.python.org/3/",
    type: "link",
    category: "cs50",
    subcategory: "python",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 609,
    title: "C Programming Tutorial",
    description: "دورة شاملة في لغة C",
    url: "https://www.tutorialspoint.com/cprogramming/",
    type: "link",
    category: "cs50",
    subcategory: "c-language",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 610,
    title: "SQL Tutorial",
    description: "تعلم SQL من الصفر",
    url: "https://www.w3schools.com/sql/",
    type: "link",
    category: "cs50",
    subcategory: "sql",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  }
];

const categoryNames = {
  cs50: "CS-50",
  math: "الرياضيات",
  physics: "الفيزياء",
  chemistry: "الكيمياء",
  statistics: "الإحصاء",
  biology: "البيولوجيا"
};

const subcategoryNames = {
  // CS50
  general: "عام",
  scratch: "سكراتش",
  "c-language": "لغة C",
  arrays: "المصفوفات",
  algorithms: "الخوارزميات",
  memory: "الذاكرة",
  "data-structures": "هياكل البيانات",
  python: "بايثون",
  sql: "SQL",
  web: "تطوير الويب",
  flask: "فلاسك",
  project: "المشروع",
  notes: "ملخصات",
  tools: "الأدوات",
  books: "كتب",
  community: "المجتمع",
  // Math
  algebra: "جبر",
  calculus: "حساب التفاضل والتكامل",
  discrete: "رياضيات منفصلة",
  linear: "جبر خطي",
  probability: "احتمالات",
  geometry: "هندسة",
  "number-theory": "نظرية الأعداد",
  // Physics
  mechanics: "ميكانيكا",
  electricity: "كهرباء",
  optics: "بصريات",
  thermo: "ديناميكا حرارية",
  // Chemistry
  general: "كيمياء عامة",
  organic: "كيمياء عضوية",
  inorganic: "كيمياء غير عضوية",
  // Statistics
  descriptive: "إحصاء وصفي",
  inferential: "إحصاء استنتاجي",
  // Biology
  genetics: "وراثة",
  cell: "أحياء خلوية",
  bioinformatics: "معلوماتية حيوية"
};
