const defaultResources = [
  // ============================================
  // CS-50 RESOURCES (40+ resources)
  // ============================================
  {
    id: 1,
    title: "CS50 Introduction to Computer Science - Harvard",
    description: "الدورة الرسمية من جامعة هارفارد لتعلم أساسيات علوم الحاسوب",
    url: "https://cs50.harvard.edu/x/",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 2,
    title: "CS50 بالعربي - كورس كامل",
    description: "ترجمة عربية كاملة لدورة CS50 من جامعة هارفارد",
    url: "https://www.youtube.com/playlist?list=PLknwEmKsW8OvsdJ64v5YljHNtt100kN6w",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 3,
    title: "CS50 بالعربي - نسخة عبدالرحمن جمال",
    description: "دورة CS50 مترجمة بالعربي由 عبدالرحمن جمال",
    url: "https://www.youtube.com/playlist?list=PLknwEmKsW8OvMsFbU9zo8oJCprAsgc4LO",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 4,
    title: "CS50 Lecture 0 - Scratch",
    description: "محاضرة introducing to computational thinking with Scratch",
    url: "https://cs50.harvard.edu/x/2024/weeks/0/",
    type: "video",
    category: "cs50",
    subcategory: "scratch",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 5,
    title: "CS50 Lecture 1 - C",
    description: "مقدمة في لغة C وبرمجة الحاسوب",
    url: "https://cs50.harvard.edu/x/2024/weeks/1/",
    type: "video",
    category: "cs50",
    subcategory: "c-language",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 6,
    title: "CS50 Lecture 2 - Arrays",
    description: "تعلم المصفوفات والبيانات في لغة C",
    url: "https://cs50.harvard.edu/x/2024/weeks/2/",
    type: "video",
    category: "cs50",
    subcategory: "arrays",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 7,
    title: "CS50 Lecture 3 - Algorithms",
    description: "خوارزميات البحث والترتيب",
    url: "https://cs50.harvard.edu/x/2024/weeks/3/",
    type: "video",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 8,
    title: "CS50 Lecture 4 - Memory",
    description: "إدارة الذاكرة في البرمجة",
    url: "https://cs50.harvard.edu/x/2024/weeks/4/",
    type: "video",
    category: "cs50",
    subcategory: "memory",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 9,
    title: "CS50 Lecture 5 - Data Structures",
    description: "هياكل البيانات المتقدمة",
    url: "https://cs50.harvard.edu/x/2024/weeks/5/",
    type: "video",
    category: "cs50",
    subcategory: "data-structures",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 10,
    title: "CS50 Lecture 6 - Python",
    description: "مقدمة في لغة بايثون",
    url: "https://cs50.harvard.edu/x/2024/weeks/6/",
    type: "video",
    category: "cs50",
    subcategory: "python",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 11,
    title: "CS50 Lecture 7 - SQL",
    description: "قواعد البيانات SQL",
    url: "https://cs50.harvard.edu/x/2024/weeks/7/",
    type: "video",
    category: "cs50",
    subcategory: "sql",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 12,
    title: "CS50 Lecture 8 - HTML, CSS, JavaScript",
    description: "تطوير الويب الأساسي",
    url: "https://cs50.harvard.edu/x/2024/weeks/8/",
    type: "video",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 13,
    title: "CS50 Lecture 9 - Flask",
    description: "تطوير تطبيقات الويب ببايثون",
    url: "https://cs50.harvard.edu/x/2024/weeks/9/",
    type: "video",
    category: "cs50",
    subcategory: "flask",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 14,
    title: "CS50 Final Project",
    description: "مشروع التخرج من CS50",
    url: "https://cs50.harvard.edu/x/2024/project/",
    type: "exercise",
    category: "cs50",
    subcategory: "project",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 15,
    title: "CS50 Study Notes - Arabic",
    description: "ملخصات دروس CS50 بالعربية",
    url: "https://cs50.harvard.edu/x/2024/notes/",
    type: "summary",
    category: "cs50",
    subcategory: "notes",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 16,
    title: "CS50 IDE - Online Compiler",
    description: "محرر الأكواد عبر الإنترنت من CS50",
    url: "https://ide.cs50.io/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 17,
    title: "كورس CS50 بالعربي - ستيجيت",
    description: "دورة CS50 مترجمة بالعربية على منصة ستيجيت",
    url: "https://www.stjegypt.com/course/555_%D9%83%D9%88%D8%B1%D8%B3-CS-%D8%A8%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A-%D8%AA%D8%B9%D9%84%D9%85-%D8%B9%D9%84%D9%88%D9%85-%D8%A7%D9%84%D8%AD%D8%A7%D8%B3%D9%88%D8%A8-%D9%88%D8%A7%D9%84%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D9%85%D8%AC%D8%A7%D9%86%D9%8B%D8%A7",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 18,
    title: "CS50 Introduction to AI with Python",
    description: "مقدمة في الذكاء الاصطناعي باستخدام بايثون",
    url: "https://cs50.harvard.edu/ai/",
    type: "video",
    category: "cs50",
    subcategory: "ai",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 19,
    title: "CS50 Web Programming with Python",
    description: "تطوير الويب باستخدام بايثون وجافاسكريبت",
    url: "https://cs50.harvard.edu/web/",
    type: "video",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 20,
    title: "CS50 Introduction to Databases with SQL",
    description: "مقدمة في قواعد البيانات باستخدام SQL",
    url: "https://cs50.harvard.edu/sql/",
    type: "video",
    category: "cs50",
    subcategory: "sql",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 21,
    title: "CS50 Introduction to Cybersecurity",
    description: "مقدمة في الأمن السيبراني",
    url: "https://cs50.harvard.edu/cybersecurity/",
    type: "video",
    category: "cs50",
    subcategory: "cybersecurity",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 22,
    title: "CS50 Mobile App Development",
    description: "تطوير تطبيقات الموبايل باستخدام React Native",
    url: "https://cs50.harvard.edu/mobile/",
    type: "video",
    category: "cs50",
    subcategory: "mobile",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 23,
    title: "Free Programming Books - GitHub",
    description: "مجموعة ضخمة من كتب البرمجة المجانية",
    url: "https://github.com/EbookFoundation/free-programming-books",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 24,
    title: "The Missing Semester of CS Education",
    description: "الفصل المفقود من تعليم علوم الحاسوب",
    url: "https://missing.csail.mit.edu/",
    type: "video",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 25,
    title: "How to Design Programs",
    description: "كيفية تصميم البرامج - كتاب مجاني",
    url: "https://htdp.org/",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 26,
    title: "W3Schools - Web Development",
    description: "تعلم تطوير الويب من W3Schools",
    url: "https://www.w3schools.com/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 27,
    title: "MDN Web Docs",
    description: "توثيق تطوير الويب من Mozilla",
    url: "https://developer.mozilla.org/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 28,
    title: "Python Official Documentation",
    description: "التوثيق الرسمي لغة بايثون",
    url: "https://docs.python.org/3/",
    type: "link",
    category: "cs50",
    subcategory: "python",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 29,
    title: "C Programming Tutorial",
    description: "دورة شاملة في لغة C",
    url: "https://www.tutorialspoint.com/cprogramming/",
    type: "link",
    category: "cs50",
    subcategory: "c-language",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 30,
    title: "SQL Tutorial",
    description: "تعلم SQL من الصفر",
    url: "https://www.w3schools.com/sql/",
    type: "link",
    category: "cs50",
    subcategory: "sql",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 31,
    title: "CS50 Study Group - Facebook",
    description: "مجموعة دراسة CS50 على فيسبوك",
    url: "https://www.facebook.com/groups/cs50/",
    type: "link",
    category: "cs50",
    subcategory: "community",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 32,
    title: "CS50 on edX",
    description: "دورة CS50 على منصة edX",
    url: "https://www.edx.org/cs50",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 33,
    title: "CS50 for Lawyers",
    description: "CS50 للمحامين - مقدمة في علوم الحاسوب",
    url: "https://cs50.harvard.edu/law/",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 34,
    title: "CS50 for Business",
    description: "CS50 للأعمال - علوم الحاسوب للأعمال",
    url: "https://cs50.harvard.edu/business/",
    type: "video",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 35,
    title: "Introduction to Algorithms (CLRS)",
    description: "مقدمة في الخوارزميات - الكتاب الشامل",
    url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/",
    type: "book",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 36,
    title: "Structure and Interpretation of Computer Programs",
    description: "هيكل وتفسير برامج الحاسوب - كتاب أيقوني",
    url: "https://mitpress-9780262512008.s3.amazonaws.com/684096ec47af4ad788596b546a8a3b59/SICPFullText.pdf",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 37,
    title: "CS50 Shorts - فيديوهات قصيرة",
    description: "فيديوهات قصيرة شرح مفاهيم CS50",
    url: "https://cs50.harvard.edu/x/2024 shorts/",
    type: "video",
    category: "cs50",
    subcategory: "notes",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 38,
    title: "CS50 Duck - مساعد البرمجة",
    description: "أداة مساعدة لتحليل الأكواد",
    url: "https://cs50.ai/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 39,
    title: "CS50 Visual Studio Code",
    description: "بيئة التطوير من CS50",
    url: "https://cs50.harvard.edu/x/2024/vscode/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 40,
    title: "CS50 Style Guide",
    description: "دليل أسلوب البرمجة في CS50",
    url: "https://cs50.harvard.edu/x/2024/style/",
    type: "link",
    category: "cs50",
    subcategory: "notes",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // MATHEMATICS RESOURCES (35+ resources)
  // ============================================
  {
    id: 100,
    title: "الرياضيات الأساسية للمبرمجين",
    description: "دورة شاملة في الأساسيات الرياضيات اللازمة للبرمجة",
    url: "https://www.khanacademy.org/math",
    type: "video",
    category: "math",
    subcategory: "algebra",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 101,
    title: "线性代数 - Linear Algebra",
    description: "جبر خطي لتعلم الذكاء الاصطناعي وتعلم الآلة",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    type: "video",
    category: "math",
    subcategory: "linear",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 102,
    title: "Calculus Made Easy",
    description: "كتاب مجاني لتعلم حساب التفاضل والتكامل",
    url: "https://www.gutenberg.org/files/33283/33283-pdf.pdf",
    type: "book",
    category: "math",
    subcategory: "calculus",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 103,
    title: "Discrete Mathematics - MIT OpenCourseWare",
    description: "رياضيات منفصلة من معهد ماساتشوستس للتقنية",
    url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/",
    type: "video",
    category: "math",
    subcategory: "discrete",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 104,
    title: "Probability and Statistics",
    description: "أساسيات الاحتمالات والإحصاء",
    url: "https://www.khanacademy.org/math/probability",
    type: "video",
    category: "math",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 105,
    title: "Mathematics for Computer Science",
    description: "كتاب الرياضيات لعلوم الحاسوب من MIT",
    url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/pages/readings/",
    type: "book",
    category: "math",
    subcategory: "discrete",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 106,
    title: "Algebra Fundamentals",
    description: "أساسيات الجبر للمبتدئين",
    url: "https://www.khanacademy.org/math/algebra",
    type: "video",
    category: "math",
    subcategory: "algebra",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 107,
    title: "Geometry Basics",
    description: "أساسيات الهندسة",
    url: "https://www.khanacademy.org/math/geometry",
    type: "video",
    category: "math",
    subcategory: "geometry",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 108,
    title: "Number Theory for Programming",
    description: "نظرية الأعداد للبرمجيات",
    url: "https://ocw.mit.edu/courses/18-781-theory-of-numbers-spring-2012/",
    type: "book",
    category: "math",
    subcategory: "number-theory",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 109,
    title: " Khan Academy - تعلم الرياضيات بالعربية",
    description: "منصة خان الأكاديمية للتعلم بالعربية",
    url: "https://ar.khanacademy.org/math",
    type: "video",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 110,
    title: "Mathematics for Machine Learning",
    description: "الرياضيات لتعلم الآلة - كتاب مجاني",
    url: "https://mml-book.github.io/",
    type: "book",
    category: "math",
    subcategory: "linear",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 111,
    title: "Trigonometry Basics",
    description: "أساسياتтриغونومتريا",
    url: "https://www.khanacademy.org/math/trigonometry",
    type: "video",
    category: "math",
    subcategory: "trigonometry",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 112,
    title: "Pre-Calculus",
    description: "مقدمة في حساب التفاضل والتكامل",
    url: "https://www.khanacademy.org/math/precalculus",
    type: "video",
    category: "math",
    subcategory: "calculus",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 113,
    title: "AP/College Calculus",
    description: "حساب التفاضل والتكامل المتقدم",
    url: "https://www.khanacademy.org/math/ap-calculus-ab",
    type: "video",
    category: "math",
    subcategory: "calculus",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 114,
    title: "Linear Algebra - Khan Academy",
    description: "جبر خطي من أكاديمية خان",
    url: "https://www.khanacademy.org/math/linear-algebra",
    type: "video",
    category: "math",
    subcategory: "linear",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 115,
    title: "Statistical Learning",
    description: "التعلم الإحصائي - كتاب مجاني",
    url: "https://www.statlearning.com/",
    type: "book",
    category: "math",
    subcategory: "statistics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 116,
    title: "Arabic Mathematics Heritage",
    description: "تراث العرب العلمي في الرياضيات والفلك",
    url: "https://www.noor-book.com/en/ebook-Tur%C4%81%E2%80%8Eth-al%CA%BBArab-al%CA%BBilm%C4%AB-fi%CC%84-alriy%C4%81%E2%80%8Ed%CC%A3%C4%ABy%C4%81%E2%80%8Et-waalfalak-pdf",
    type: "book",
    category: "math",
    subcategory: "history",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 117,
    title: "Open Library - Arab Mathematics",
    description: "مكتبة مفتوحة - كتب رياضيات عربية",
    url: "https://openlibrary.org/subjects/arab_mathematics",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 118,
    title: "Mathematics for Programmers",
    description: "كتاب الرياضيات للمبرمجين",
    url: "https://www.manning.com/books/math-for-programmers",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 119,
    title: "Think Python - Free Book",
    description: "التفكير ببايثون - كتاب مجاني",
    url: "https://greenteapress.com/thinkpython2/html/index.html",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 120,
    title: "Arabic Collections Online - Mathematics",
    description: "المجموعات العربية عبر الإنترنت - رياضيات",
    url: "http://dlib.nyu.edu/aco/browse/?page=1",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 121,
    title: "كتاب الرياضيات -الثالث متوسط",
    description: "كتاب الرياضيات للصف الثالث المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb3/2025-2026/كتاب%20الرياضيات%20الثالث%20متوسط.pdf",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 122,
    title: "كتاب الرياضيات - الأول متوسط",
    description: "كتاب الرياضيات للصف الأول المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb1/2025-2026/كتاب%20الرياضيات%20اول%20متوسط.pdf",
    type: "book",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 123,
    title: "MIT Mathematics Courses",
    description: "دورات رياضيات من MIT مفتوحة المصدر",
    url: "https://ocw.mit.edu/courses/mathematics/",
    type: "video",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 124,
    title: "3Blue1Brown - Math Visualized",
    description: "تصور الرياضيات بطريقة بصرية جميلة",
    url: "https://www.3blue1brown.com/",
    type: "video",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 125,
    title: "Kottap - منصة عربية للعلوم",
    description: "منصة عربية مجانية للمحتوى العلمي الموثوق",
    url: "https://kottap.com/",
    type: "link",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 126,
    title: "Math Exercises for You",
    description: "تمارين رياضيات تفاعلية",
    url: "https://www.math-exercises.com/",
    type: "exercise",
    category: "math",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 127,
    title: "Wolfram Alpha - Math Tool",
    description: "أداة حسابات رياضية متقدمة",
    url: "https://www.wolframalpha.com/",
    type: "link",
    category: "math",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 128,
    title: "Mathway - Math Solver",
    description: "حل المسائل الرياضية",
    url: "https://www.mathway.com/",
    type: "link",
    category: "math",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 129,
    title: "Desmos Graphing Calculator",
    description: "آلة حاسبة رسوم بيانية مجانية",
    url: "https://www.desmos.com/calculator",
    type: "link",
    category: "math",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 130,
    title: "GeoGebra - Math Tools",
    description: "أدوات رياضيات تفاعلية",
    url: "https://www.geogebra.org/",
    type: "link",
    category: "math",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // PHYSICS RESOURCES (25+ resources)
  // ============================================
  {
    id: 200,
    title: "Physics for Scientists and Engineers",
    description: "فيزياء للمهندسين والعلماء",
    url: "https://www.khanacademy.org/science/physics",
    type: "video",
    category: "physics",
    subcategory: "mechanics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 201,
    title: "Classical Mechanics - MIT",
    description: "ميكانيكا كلاسيكية من MIT",
    url: "https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/",
    type: "video",
    category: "physics",
    subcategory: "mechanics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 202,
    title: "Electricity and Magnetism",
    description: "الكهرباء والمغناطيسية",
    url: "https://www.khanacademy.org/science/physics/electric-charge-field",
    type: "video",
    category: "physics",
    subcategory: "electricity",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 203,
    title: "Thermodynamics Basics",
    description: "أساسيات الديناميكا الحرارية",
    url: "https://www.khanacademy.org/science/physics/thermodynamics",
    type: "video",
    category: "physics",
    subcategory: "thermo",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 204,
    title: "Optics and Waves",
    description: "البصريات والموجات",
    url: "https://www.khanacademy.org/science/physics/waves-optics",
    type: "video",
    category: "physics",
    subcategory: "optics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 205,
    title: "Physics for Computer Science",
    description: "فيزياء مفيدة لعلوم الحاسوب",
    url: "https://www.edx.org/course/classical-mechanics",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 206,
    title: "الفيزياء للجميع - Archive.org",
    description: "كتاب الفيزياء للجميع متوفر على الإنترنت",
    url: "https://archive.org/details/physics-for-everybody",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 207,
    title: "كتاب الفيزياء -الثالث متوسط",
    description: "كتاب الفيزياء للصف الثالث المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb3/2025-2026/كتاب%20الفيزياء%20الثالث%20متوسط.pdf",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 208,
    title: "كتاب الفيزياء - الأول متوسط",
    description: "كتاب الفيزياء للصف الأول المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb1/2025-2026/كتاب%20الفيزياء%20اول%20متوسط.pdf",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 209,
    title: "Physics Books - Archive.org",
    description: "مجموعة كتب فيزياء على الإنترنت",
    url: "https://archive.org/details/physics_books_",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 210,
    title: "MIT Physics Courses",
    description: "دورات فيزياء من MIT مفتوحة المصدر",
    url: "https://ocw.mit.edu/courses/physics/",
    type: "video",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 211,
    title: "Khan Academy Physics Arabic",
    description: "فيزياء من أكاديمية خان بالعربية",
    url: "https://ar.khanacademy.org/science/physics",
    type: "video",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 212,
    title: "Physics Classroom",
    description: "صفحة الفيزياء التعليمية",
    url: "https://www.physicsclassroom.com/",
    type: "link",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 213,
    title: "HyperPhysics",
    description: "موسوعة الفيزياء التفاعلية",
    url: "https://hyperphysics.phy-astr.gsu.edu/",
    type: "link",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 214,
    title: "PhET Simulations",
    description: "محاكاة فيزياء تفاعلية مجانية",
    url: "https://phet.colorado.edu/",
    type: "link",
    category: "physics",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 215,
    title: "Physics Problems - Free",
    description: "مسائل فيزياء مجانية مع حلول",
    url: "https://www.physicsproblems.org/",
    type: "exercise",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 216,
    title: "Electromagnetism - MIT",
    description: "الكهرباء والمغناطيسية من MIT",
    url: "https://ocw.mit.edu/courses/8-02-physics-ii-electricity-and-magnetism-spring-2019/",
    type: "video",
    category: "physics",
    subcategory: "electricity",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 217,
    title: "Quantum Physics - MIT",
    description: "فيزياء كمومية من MIT",
    url: "https://ocw.mit.edu/courses/8-04-quantum-physics-i-spring-2016/",
    type: "video",
    category: "physics",
    subcategory: "quantum",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 218,
    title: "Relativity - Einstein",
    description: "نظرية النسبية - آينشتاين",
    url: "https://www.gutenberg.org/files/30155/30155-pdf.pdf",
    type: "book",
    category: "physics",
    subcategory: "relativity",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 219,
    title: "Physics for Everyone",
    description: "فيزياء للجميع - كتب مجانية",
    url: "https://archive.org/details/physics-for-everybody",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 220,
    title: "YA ATAKREH AL FIZIYA",
    description: "يا تكره الفيزياء - كتاب ممتع",
    url: "https://download-pdf-ebooks.com/",
    type: "book",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 221,
    title: "Physics Video Lectures",
    description: "محاضرات فيزياء بالفيديو",
    url: "https://www.youtube.com/playlist?list=PLyQSNpYmYFaHJhMYl2QnOY7ZJQKbJDJL",
    type: "video",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 222,
    title: "Physics Calculators",
    description: "آلات حاسبة فيزيائية مجانية",
    url: "https://www.calculatorsoup.com/",
    type: "link",
    category: "physics",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 223,
    title: "Physics Science Fair Projects",
    description: "مشاريع علمية في الفيزياء",
    url: "https://www.sciencebuddies.org/science-fair-projects/ideas/physics",
    type: "exercise",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 224,
    title: "Physics for Kids",
    description: "فيزياء للأطفال - أساسيات مبسطة",
    url: "https://www.ducksters.com/science/physics.php",
    type: "link",
    category: "physics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // CHEMISTRY RESOURCES (25+ resources)
  // ============================================
  {
    id: 300,
    title: "Chemistry - Khan Academy",
    description: "الكيمياء العامة من أكاديمية خان",
    url: "https://www.khanacademy.org/science/chemistry",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 301,
    title: "Organic Chemistry Basics",
    description: "أساسيات الكيمياء العضوية",
    url: "https://www.khanacademy.org/science/organic-chemistry",
    type: "video",
    category: "chemistry",
    subcategory: "organic",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 302,
    title: "General Chemistry - MIT",
    description: "كيمياء عامة من MIT",
    url: "https://ocw.mit.edu/courses/5-111-principles-of-chemical-science-fall-2014/",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 303,
    title: "Chemistry for Programming",
    description: "كيمياء مفيدة للمبرمجين - أساسياتatoms والجزيئات",
    url: "https://www.chemguide.co.uk/",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 304,
    title: "كتاب الكيمياء -الثالث متوسط",
    description: "كتاب الكيمياء للصف الثالث المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb3/2025-2026/كتاب%20الكيمياء%20الثالث%20متوسط.pdf",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 305,
    title: "كتاب الكيمياء - الأول متوسط",
    description: "كتاب الكيمياء للصف الأول المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb1/2025-2026/كتاب%20الكيمياء%20اول%20متوسط.pdf",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 306,
    title: "Khan Academy Chemistry Arabic",
    description: "كيمياء من أكاديمية خان بالعربية",
    url: "https://ar.khanacademy.org/science/chemistry",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 307,
    title: "MIT Chemistry Courses",
    description: "دورات كيمياء من MIT مفتوحة المصدر",
    url: "https://ocw.mit.edu/courses/chemistry/",
    type: "video",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 308,
    title: "Periodic Table - Interactive",
    description: "الجدول الدوري التفاعلي",
    url: "https://ptable.com/",
    type: "link",
    category: "chemistry",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 309,
    title: "Chemistry LibreTexts",
    description: "نصوص كيمياء مجانية",
    url: "https://chem.libretexts.org/",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 310,
    title: "ChemCollective",
    description: "مشاريع كيمياء تفاعلية",
    url: "http://chemcollective.org/",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 311,
    title: "PhET Chemistry Simulations",
    description: "محاكاة كيمياء تفاعلية",
    url: "https://phet.colorado.edu/en/simulations/filter?subjects=chemistry",
    type: "link",
    category: "chemistry",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 312,
    title: "Chemical Education - ACS",
    description: "تعليم الكيمياء - الجمعية الكيميائية الأمريكية",
    url: "https://www.acs.org/education.html",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 313,
    title: "Khan Academy - Biochemistry",
    description: "كيمياء حيوية من أكاديمية خان",
    url: "https://www.khanacademy.org/science/biology/chemistry--of-life",
    type: "video",
    category: "chemistry",
    subcategory: "biochemistry",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 314,
    title: "Chemistry - OpenStax",
    description: "كتاب كيمياء مجاني من OpenStax",
    url: "https://openstax.org/subjects/science",
    type: "book",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 315,
    title: "Chemistry Experiments Online",
    description: "تجارب كيمياء عبر الإنترنت",
    url: "https://www.chemeddl.org/resources/ptable/",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 316,
    title: "Organic Chemistry Portal",
    description: "بوابة الكيمياء العضوية",
    url: "https://www.organic-chemistry.org/",
    type: "link",
    category: "chemistry",
    subcategory: "organic",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 317,
    title: "Inorganic Chemistry - MIT",
    description: "كيمياء غير عضوية من MIT",
    url: "https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/",
    type: "video",
    category: "chemistry",
    subcategory: "inorganic",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 318,
    title: "Physical Chemistry - Atkins",
    description: "كيمياء فيزيائية - كتاب شهير",
    url: "https://www.pearson.com/en-us/subject-catalog/p/physical-chemistry/P200000003194",
    type: "book",
    category: "chemistry",
    subcategory: "physical",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 319,
    title: "Chemistry Calculator",
    description: "آلة حاسبة كيميائية",
    url: "https://www.calculatoratoz.com/en/chemistry-calculators/",
    type: "link",
    category: "chemistry",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 320,
    title: "Chemical Elements - Database",
    description: "قاعدة بيانات العناصر الكيميائية",
    url: "https://www.webelements.com/",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 321,
    title: "Molecular Geometry",
    description: "هندسة الجزيئات التفاعلية",
    url: "https://molview.org/",
    type: "link",
    category: "chemistry",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 322,
    title: "ChemSpider - Chemical Database",
    description: "قاعدة بيانات المواد الكيميائية",
    url: "https://www.chemspider.com/",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 323,
    title: "Chemistry Problems",
    description: "مسائل كيمياء مع حلول",
    url: "https://www.chemproblems.com/",
    type: "exercise",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 324,
    title: "Chemistry for Kids",
    description: "كيمياء للأطفال - أساسيات مبسطة",
    url: "https://www.ducksters.com/science/chemistry.php",
    type: "link",
    category: "chemistry",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // STATISTICS RESOURCES (25+ resources)
  // ============================================
  {
    id: 400,
    title: "Statistics and Probability",
    description: "الإحصاء والاحتمالات من أكاديمية خان",
    url: "https://www.khanacademy.org/math/statistics-probability",
    type: "video",
    category: "statistics",
    subcategory: "descriptive",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 401,
    title: "Introduction to Statistical Learning",
    description: "مقدمة في التعلم الإحصائي",
    url: "https://www.statlearning.com/",
    type: "book",
    category: "statistics",
    subcategory: "inferential",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 402,
    title: "Probability for Computer Science",
    description: "الاحتمالات لعلوم الحاسوب",
    url: "https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/",
    type: "video",
    category: "statistics",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 403,
    title: "Think Stats - Free Book",
    description: "كتاب مجاني عن التفكير الإحصائي",
    url: "https://greenteapress.com/thinkstats2/html/index.html",
    type: "book",
    category: "statistics",
    subcategory: "descriptive",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 404,
    title: "Khan Academy Statistics Arabic",
    description: "إحصاء من أكاديمية خان بالعربية",
    url: "https://ar.khanacademy.org/math/statistics-probability",
    type: "video",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 405,
    title: "MIT Statistics Courses",
    description: "دورات إحصاء من MIT مفتوحة المصدر",
    url: "https://ocw.mit.edu/courses/statistics/",
    type: "video",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 406,
    title: "Statistics - OpenStax",
    description: "كتاب إحصاء مجاني من OpenStax",
    url: "https://openstax.org/details/books/introductory-statistics",
    type: "book",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 407,
    title: "Seeing Theory - Visual Stats",
    description: "نظرية الإحصاء بصرياً",
    url: "https://seeing-theory.brown.edu/",
    type: "link",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 408,
    title: "Stat Trek - Statistics Tutorial",
    description: "دروس إحصاء من Stat Trek",
    url: "https://stattrek.com/",
    type: "link",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 409,
    title: "Statistics How To",
    description: "كيف تفعل الإحصاء - دليل شامل",
    url: "https://www.statisticshowto.com/",
    type: "link",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 410,
    title: "R Programming for Statistics",
    description: "برمجة R للإحصاء",
    url: "https://www.coursera.org/learn/r-programming",
    type: "video",
    category: "statistics",
    subcategory: "programming",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 411,
    title: "Python for Statistics",
    description: "بايثون للإحصاء",
    url: "https://www.coursera.org/learn/statistical-thinking-python",
    type: "video",
    category: "statistics",
    subcategory: "programming",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 412,
    title: "Statistics Calculator",
    description: "آلة حاسبة إحصائية",
    url: "https://www.calculator.net/statistics-calculator.html",
    type: "link",
    category: "statistics",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 413,
    title: "Wolfram Statistics",
    description: "أدوات إحصاء من Wolfram",
    url: "https://www.wolfram.com/mathematica/",
    type: "link",
    category: "statistics",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 414,
    title: "Statistics Video Lectures",
    description: "محاضرات إحصاء بالفيديو",
    url: "https://www.youtube.com/playlist?list=PL2SOU6wwxB0uwwH80KTQ6ht66KWxbzTIo",
    type: "video",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 415,
    title: "Khan Academy - Data Analysis",
    description: "تحليل البيانات من أكاديمية خان",
    url: "https://www.khanacademy.org/math/statistics-probability",
    type: "video",
    category: "statistics",
    subcategory: "descriptive",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 416,
    title: "Statistics - LibreTexts",
    description: "نصوص إحصاء مجانية",
    url: "https://stats.libretexts.org/",
    type: "book",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 417,
    title: "Probability - Khan Academy",
    description: "الاحتمالات من أكاديمية خان",
    url: "https://www.khanacademy.org/math/probability",
    type: "video",
    category: "statistics",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 418,
    title: "Statistical Inference",
    description: "الاستدلال الإحصائي",
    url: "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/",
    type: "video",
    category: "statistics",
    subcategory: "inferential",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 419,
    title: "Regression Analysis",
    description: "تحليل الانحدار",
    url: "https://www.statisticshowto.com/probability-and-statistics/regression-analysis/",
    type: "link",
    category: "statistics",
    subcategory: "inferential",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 420,
    title: "Statistics for Data Science",
    description: "إحصاء لعلم البيانات",
    url: "https://www.coursera.org/specializations/statistics-with-python",
    type: "video",
    category: "statistics",
    subcategory: "data-science",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 421,
    title: "Statistics - MIT OCW",
    description: "إحصاء من MIT مفتوح المصدر",
    url: "https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/",
    type: "video",
    category: "statistics",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 422,
    title: "Think Bayes - Free Book",
    description: "التفكير باحتمالات بايز",
    url: "https://greenteapress.com/thinkbayes/html/index.html",
    type: "book",
    category: "statistics",
    subcategory: "probability",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 423,
    title: "Statistics Problems",
    description: "مسائل إحصاء مع حلول",
    url: "https://www.symbolab.com/solver/statistics-calculator",
    type: "link",
    category: "statistics",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 424,
    title: "R Tutorial",
    description: "دليل R للإحصاء",
    url: "https://www.statmethods.net/",
    type: "link",
    category: "statistics",
    subcategory: "programming",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // BIOLOGY RESOURCES (25+ resources)
  // ============================================
  {
    id: 500,
    title: "Biology - Khan Academy",
    description: "علم الأحياء من أكاديمية خان",
    url: "https://www.khanacademy.org/science/biology",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 501,
    title: "Introduction to Biology - MIT",
    description: "مقدمة في علم الأحياء من MIT",
    url: "https://ocw.mit.edu/courses/7-01-introductory-biology-fall-2011/",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 502,
    title: "Genetics and Genomics",
    description: "علم الوراثة والجينوم",
    url: "https://www.khanacademy.org/science/biology/classical-genetics",
    type: "video",
    category: "biology",
    subcategory: "genetics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 503,
    title: "Cell Biology",
    description: "علم الأحياء الخلوي",
    url: "https://www.khanacademy.org/science/biology/cells",
    type: "video",
    category: "biology",
    subcategory: "cell",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 504,
    title: "Bioinformatics for Programmers",
    description: "علم المعلومات الحيوية للمبرمجين",
    url: "https://www.coursera.org/learn/bioinformatics",
    type: "video",
    category: "biology",
    subcategory: "bioinformatics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 505,
    title: "كتاب الأحياء -الثالث متوسط",
    description: "كتاب الأحياء للصف الثالث المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb3/2025-2026/كتاب%20الاحياء%20الثالث%20متوسط.pdf",
    type: "book",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 506,
    title: "كتاب الأحياء - الأول متوسط",
    description: "كتاب الأحياء للصف الأول المتوسط - المنهج العراقي",
    url: "https://bk2.shr4.com/books/bb1/2025-2026/كتاب%20الاحياء%20اول%20متوسط.pdf",
    type: "book",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 507,
    title: "Khan Academy Biology Arabic",
    description: "أحياء من أكاديمية خان بالعربية",
    url: "https://ar.khanacademy.org/science/biology",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 508,
    title: "MIT Biology Courses",
    description: "دورات أحياء من MIT مفتوحة المصدر",
    url: "https://ocw.mit.edu/courses/biology/",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 509,
    title: "Biology LibreTexts",
    description: "نصوص أحياء مجانية",
    url: "https://bio.libretexts.org/",
    type: "book",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 510,
    title: "Cell Interactive",
    description: "الخلية التفاعلية",
    url: "https://www.cellsalive.com/",
    type: "link",
    category: "biology",
    subcategory: "cell",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 511,
    title: "DNA Learning Center",
    description: "مركز تعلم الحمض النووي",
    url: "https://dnalc.org/",
    type: "link",
    category: "biology",
    subcategory: "genetics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 512,
    title: "Biology Dictionary",
    description: "قاموس الأحياء",
    url: "https://www.biologyonline.com/dictionary",
    type: "link",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 513,
    title: "PhET Biology Simulations",
    description: "محاكاة أحياء تفاعلية",
    url: "https://phet.colorado.edu/en/simulations/filter?subjects=biology",
    type: "link",
    category: "biology",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 514,
    title: "Evolution - Understanding",
    description: "فهم التطور",
    url: "https://www.khanacademy.org/science/biology/classical-genetics/evolution",
    type: "video",
    category: "biology",
    subcategory: "evolution",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 515,
    title: "Human Biology - Khan Academy",
    description: "الأحياء البشرية",
    url: "https://www.khanacademy.org/science/biology/human-biology",
    type: "video",
    category: "biology",
    subcategory: "human",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 516,
    title: "Ecology - Khan Academy",
    description: "علم البيئة",
    url: "https://www.khanacademy.org/science/biology/ecology",
    type: "video",
    category: "biology",
    subcategory: "ecology",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 517,
    title: "Molecular Biology",
    description: "الأحياء الجزيئية",
    url: "https://ocw.mit.edu/courses/7-28-molecular-biology-spring-2005/",
    type: "video",
    category: "biology",
    subcategory: "molecular",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 518,
    title: "Biology - OpenStax",
    description: "كتاب أحياء مجاني من OpenStax",
    url: "https://openstax.org/details/books/biology-2e",
    type: "book",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 519,
    title: "Neuroscience - Khan Academy",
    description: "علم الأعصاب",
    url: "https://www.khanacademy.org/science/biology/human-biology/neurology-brain",
    type: "video",
    category: "biology",
    subcategory: "neuroscience",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 520,
    title: "Microbiology - MIT",
    description: "علم الأحياء الدقيقة",
    url: "https://ocw.mit.edu/courses/20-106-microbiology-fall-2003/",
    type: "video",
    category: "biology",
    subcategory: "microbiology",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 521,
    title: "Bioethics - Harvard",
    description: "أخلاقيات الحيوية",
    url: "https://www.edx.org/learn/bioethics",
    type: "video",
    category: "biology",
    subcategory: "ethics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 522,
    title: "Biology Video Lectures",
    description: "محاضرات أحياء بالفيديو",
    url: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtMwmepBjTSG593eG7ObzO7s",
    type: "video",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 523,
    title: "Genetics - NIH",
    description: "علم الوراثة - المعهد الوطني للصحة",
    url: "https://www.genome.gov/",
    type: "link",
    category: "biology",
    subcategory: "genetics",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 524,
    title: "Biology Experiments",
    description: "تجارب أحياء تفاعلية",
    url: "https://www.biologyexperiments4all.com/",
    type: "exercise",
    category: "biology",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },

  // ============================================
  // EXTRA RESOURCES
  // ============================================
  {
    id: 600,
    title: "Coursera - Free Courses",
    description: "دورات مجانية على Coursera",
    url: "https://www.coursera.org/courses",
    type: "link",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 601,
    title: "edX - Free Courses",
    description: "دورات مجانية على edX",
    url: "https://www.edx.org/browse",
    type: "link",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 602,
    title: "MIT OpenCourseWare",
    description: " MIT محتوى مفتوح",
    url: "https://ocw.mit.edu/",
    type: "link",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 603,
    title: "Khan Academy Arabic",
    description: "أكاديمية خان بالعربية",
    url: "https://ar.khanacademy.org/",
    type: "link",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 604,
    title: "FreeCodeCamp",
    description: "تعلم البرمجة مجاناً",
    url: "https://www.freecodecamp.org/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 605,
    title: "The Odin Project",
    description: "مشروع أودين لتطوير الويب",
    url: "https://www.theodinproject.com/",
    type: "link",
    category: "cs50",
    subcategory: "web",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 606,
    title: "Codecademy",
    description: "تعلم البرمجة تفاعلياً",
    url: "https://www.codecademy.com/",
    type: "link",
    category: "cs50",
    subcategory: "general",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 607,
    title: "LeetCode",
    description: "تمارين برمجية للتدريب",
    url: "https://leetcode.com/",
    type: "exercise",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 608,
    title: "HackerRank",
    description: "تحديات برمجية",
    url: "https://www.hackerrank.com/",
    type: "exercise",
    category: "cs50",
    subcategory: "algorithms",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 609,
    title: "GitHub Student Developer Pack",
    description: "حزمة المطورين الطلابية من GitHub",
    url: "https://education.github.com/pack",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 610,
    title: "Visual Studio Code",
    description: "محرر أكواد مجاني من Microsoft",
    url: "https://code.visualstudio.com/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 611,
    title: "GitHub",
    description: "منصة استضافة المشاريع",
    url: "https://github.com/",
    type: "link",
    category: "cs50",
    subcategory: "tools",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 612,
    title: "Stack Overflow",
    description: "مجتمع المبرمجين للأسئلة",
    url: "https://stackoverflow.com/",
    type: "link",
    category: "cs50",
    subcategory: "community",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 613,
    title: "Dev.to",
    description: "مجتمع المطورين",
    url: "https://dev.to/",
    type: "link",
    category: "cs50",
    subcategory: "community",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 614,
    title: "Reddit - r/learnprogramming",
    description: "subreddit لتعلم البرمجة",
    url: "https://www.reddit.com/r/learnprogramming/",
    type: "link",
    category: "cs50",
    subcategory: "community",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 615,
    title: "Noor Book - Free Arabic Books",
    description: "مكتبة نور - كتب عربية مجانية",
    url: "https://www.noor-book.com/",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 616,
    title: "Kutub Network - Free Books",
    description: "شبكة الكتب - كتب مجانية",
    url: "https://www.kutub.network/",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 617,
    title: "Archive.org - Arabic Books",
    description: "كتب عربية على الإنترنت",
    url: "https://archive.org/details/booksbylanguage_arabic",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 618,
    title: "Digital Arabic Collections",
    description: "المجموعات الرقمية العربية",
    url: "http://dlib.nyu.edu/aco/browse/?page=1",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 619,
    title: "Maktabeti - 3000 Books",
    description: "مكتبتي - 3000 كتاب للتحميل",
    url: "https://maktabeti.com/3000-%D8%A3%D8%B7%D8%B1%D9%88%D8%AD%D8%A9-%D9%84%D9%84%D8%AA%D8%AD%D9%85%D9%8A%D9%84-%D8%A7%D9%84%D9%85%D8%AC%D8%A7%D9%86%D9%8A-%D8%A8%D8%B5%D9%8A%D8%BA%D8%A9-pdf",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  },
  {
    id: 620,
    title: "YemBooks - Yemeni Curriculum",
    description: "كتب المنهج اليمني",
    url: "https://yembooks.com/books",
    type: "book",
    category: "cs50",
    subcategory: "books",
    bookmarked: false,
    progress: 0,
    dateAdded: "2024-01-01"
  }
];

const categoryNames = {
  cs50: "CS-50",
  math: "الرياضيات",
  physics: "الفيزياء",
  chemistry: "الكيمياء",
  statistics: "الإحصاء",
  biology: "البيولوجيا"
};

const subcategoryNames = {
  // CS50
  general: "عام",
  scratch: "سكراتش",
  "c-language": "لغة C",
  arrays: "المصفوفات",
  algorithms: "الخوارزميات",
  memory: "الذاكرة",
  "data-structures": "هياكل البيانات",
  python: "بايثون",
  sql: "SQL",
  web: "تطوير الويب",
  flask: "فلاسك",
  project: "المشروع",
  notes: "ملخصات",
  tools: "الأدوات",
  books: "كتب",
  community: "المجتمع",
  ai: "الذكاء الاصطناعي",
  cybersecurity: "الأمن السيبراني",
  mobile: "الموبايل",
  // Math
  algebra: "جبر",
  calculus: "حساب التفاضل والتكامل",
  discrete: "رياضيات منفصلة",
  linear: "جبر خطي",
  probability: "احتمالات",
  geometry: "هندسة",
  "number-theory": "نظرية الأعداد",
  trigonometry: "триغونومتريا",
  statistics: "إحصاء",
  history: "تاريخ",
  // Physics
  mechanics: "ميكانيكا",
  electricity: "كهرباء",
  optics: "بصريات",
  thermo: "ديناميكا حرارية",
  quantum: "كمومية",
  relativity: "نسبية",
  // Chemistry
  organic: "كيمياء عضوية",
  inorganic: "كيمياء غير عضوية",
  physical: "كيمياء فيزيائية",
  biochemistry: "كيمياء حيوية",
  // Statistics
  descriptive: "إحصاء وصفي",
  inferential: "إحصاء استنتاجي",
  programming: "برمجة",
  "data-science": "علم البيانات",
  // Biology
  genetics: "وراثة",
  cell: "خلوية",
  bioinformatics: "معلوماتية حيوية",
  evolution: "تطور",
  human: "بشرية",
  ecology: "بيئة",
  molecular: "جزيئية",
  neuroscience: "أعصاب",
  microbiology: "دقيقة",
  ethics: "أخلاق"
};
